import mongoose, { Schema, Model, Document, Types } from 'mongoose';

/**
 * LedgerEntry — immutable financial audit log
 *
 * ── The Ledger Pattern ─────────────────────────────────────────────────────────
 * Every financial event in the platform creates one or more LedgerEntry documents.
 * Entries are NEVER updated after creation — only created. This gives:
 *
 *   - Complete tamper-proof audit trail for every EGP that flows through the platform
 *   - KPIs always derived from aggregations, never from mutable counters
 *   - Easy reconciliation: sum all entries of a type = total for that category
 *
 * ── Entry types and their sign convention ─────────────────────────────────────
 *
 * When a manual order is approved (admin verifies receipt):
 *   GROSS_REVENUE         (+)  full sale amount collected from student
 *   GATEWAY_FEE           (-)  payment processing cost (0% default, configurable)
 *   TRAINER_COMMISSION    (-)  trainer's share credited to their Wallet
 *   VOLUNTEER_COMMISSION  (-)  affiliate's share credited to their Wallet (if ref)
 *   NET_PLATFORM_PROFIT   (+)  remainder retained by the platform
 *
 * When a payout is settled by admin:
 *   PAYOUT_SETTLED        (-)  funds disbursed to trainer or volunteer
 *
 * When admin logs an operating cost:
 *   MANUAL_EXPENSE        (-)  servers, salaries, ads, etc.
 *
 * ── KPI derivation ────────────────────────────────────────────────────────────
 *   Total Gross Volume     = Σ GROSS_REVENUE
 *   Total Platform Profit  = Σ NET_PLATFORM_PROFIT − Σ MANUAL_EXPENSE
 *   Total Liabilities      = Σ available balances (from Wallet, not Ledger)
 *   Revenue by Month       = $group by { year, month } on GROSS_REVENUE entries
 */

export const LedgerEntryType = {
    GROSS_REVENUE:        'GROSS_REVENUE',
    GATEWAY_FEE:          'GATEWAY_FEE',
    TRAINER_COMMISSION:   'TRAINER_COMMISSION',
    VOLUNTEER_COMMISSION: 'VOLUNTEER_COMMISSION',
    NET_PLATFORM_PROFIT:  'NET_PLATFORM_PROFIT',
    PAYOUT_SETTLED:       'PAYOUT_SETTLED',
    MANUAL_EXPENSE:       'MANUAL_EXPENSE',
} as const;

export type LedgerEntryType = typeof LedgerEntryType[keyof typeof LedgerEntryType];

export interface ILedgerEntry extends Document {
    /**
     * The type of financial event.
     * This is the primary dimension for aggregation queries.
     */
    entryType: LedgerEntryType;

    /**
     * Amount in EGP (always positive).
     * The direction (income vs expense) is encoded by entryType, not sign.
     * This avoids sign errors in aggregation pipelines.
     */
    amount: number;

    /**
     * Reference to the Order that triggered this entry.
     * Null for PAYOUT_SETTLED and MANUAL_EXPENSE entries.
     */
    orderId?: Types.ObjectId;

    /**
     * Which course this entry relates to (for per-course P&L reporting).
     * Null for PAYOUT_SETTLED and MANUAL_EXPENSE entries.
     */
    courseId?: Types.ObjectId;

    /**
     * Which user's wallet was credited/debited.
     * Set for TRAINER_COMMISSION, VOLUNTEER_COMMISSION, and PAYOUT_SETTLED.
     * Null for GROSS_REVENUE, GATEWAY_FEE, NET_PLATFORM_PROFIT, MANUAL_EXPENSE.
     */
    userId?: Types.ObjectId;

    /**
     * Human-readable description for the admin ledger view.
     * Auto-generated by the split engine, or entered by admin for expenses.
     */
    note: string;

    /**
     * For TRAINER_COMMISSION, represents the unlock status.
     * 'PENDING' during the 14-day hold, 'AVAILABLE' after, 'PAID' when withdrawn.
     */
    status?: 'PENDING' | 'AVAILABLE' | 'PAID';

    /**
     * For TRAINER_COMMISSION, when this entry becomes available (createdAt + 14 days).
     */
    unlocksAt?: Date;

    createdAt: Date;
}

// ─── Schema ────────────────────────────────────────────────────────────────────

const LedgerEntrySchema = new Schema<ILedgerEntry>(
    {
        entryType: {
            type:     String,
            enum:     Object.values(LedgerEntryType),
            required: [true, 'Entry type is required'],
            index:    true,
        },
        amount: {
            type:     Number,
            required: [true, 'Amount is required'],
            min:      [0, 'Ledger amounts are always positive — direction is encoded in entryType'],
        },
        orderId: {
            type: Schema.Types.ObjectId,
            ref:  'Order',
            // sparse: indexed only when present (most expense entries have no orderId)
        },
        courseId: {
            type: Schema.Types.ObjectId,
            ref:  'Course',
        },
        userId: {
            type: Schema.Types.ObjectId,
            ref:  'User',
        },
        note: {
            type:     String,
            required: [true, 'Note is required for audit trail'],
            trim:     true,
            maxlength: [500, 'Note cannot exceed 500 characters'],
        },
        status: {
            type: String,
            enum: ['PENDING', 'AVAILABLE', 'PAID'],
        },
        unlocksAt: {
            type: Date,
        },
    },
    {
        timestamps: true, // Need updatedAt if we are going to change status
    }
);

// ─── Indexes ───────────────────────────────────────────────────────────────────

// Primary KPI aggregation: "total of all GROSS_REVENUE entries"
LedgerEntrySchema.index({ entryType: 1, createdAt: -1 });

// Revenue over time: group by month for charts
LedgerEntrySchema.index({ createdAt: -1 });

// Order audit trail: "all ledger entries for order X"
LedgerEntrySchema.index({ orderId: 1 }, { sparse: true });

// User P&L: "all entries affecting user Y"
LedgerEntrySchema.index({ userId: 1, entryType: 1 }, { sparse: true });

// Per-course profitability
LedgerEntrySchema.index({ courseId: 1, entryType: 1 }, { sparse: true });

// ─── Model ─────────────────────────────────────────────────────────────────────

const LedgerEntry: Model<ILedgerEntry> =
    mongoose.models.LedgerEntry ||
    mongoose.model<ILedgerEntry>('LedgerEntry', LedgerEntrySchema);

export default LedgerEntry;
